[package]
name = "Raytracing_in_One_Weekend"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Kensuke Saito"]
repository = "https://github.com/bonohub13/Raytracing_in_One_Weekend"

[dependencies]
anyhow = "1.0.100"
rtiow = { version = "0.1.0", path = "rtiow" }
winit = "0.30.12"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[profile.dev]
incremental = true

[profile.release]
strip = true
opt-level = 3
lto = true

[profile.release-debug]
inherits = "release"
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = true
