[package]
name = "raytracing_in_one_weekend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
rtiow = { version = "0.1.0", path = "rtiow" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
