[package]
name = "rtiow"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
image = "0.25.2"
indicatif = {version = "0.17.8", features = ["rayon"]}
rand = "0.8.5"
rayon = "1.10.0"
stb_image = "0.3.0"
thiserror = "1.0.64"
